Finish writing the description of the UserUseCaseInteractor
CSC207-2022F-UofT/course-project-group-140-q-a-forum pull request #38
Opened 2022-11-15 03:42 UTC by jasongangquanzhang

UserUseCaseInteractor structure update

2022-11-15 05:39 UTC, jasongangquanzhang commented
I created some check functions and their description. Some of them will be called in the main function createAccount. I kept the verifyEmail function but there is a small conflict in how we can verify the email.

2022-11-15 05:51 UTC, blairyeung approved these changes
Good comments. For the import message you can just import java.util instead of importing two.

2022-11-16 01:58 UTC, JY3150 submitted a review, later dismissed
Good instructions for how to complete these methods. But I think next time you can put the specific instructions in the method itself rather than in the javadoc. I believe javadoc is meant to give users a brief introduction about what this method does, what parameters it requires and what kind of output it will generate, but the user does not need to know how exactly the method is implemented. I will approve this time but next time please put these instructions down in the method.

2022-11-16 20:20 UTC, jasongangquanzhang commented
@Teinble You are right. Some functions should pass a hashmap to the controller, such as the first one createAccount. However, I wrote some help functions that would be called in the createAccount to help judge the situation. For those functions, they should retrun a boolean.

2022-11-17 03:49 UTC, Teinble commented on src/use_cases/UserUseCaseInteractor.java
> +    public String createUser(Map<String,ArrayList<String>> user){
Question: Why in the value of  map is an arraylist? I suppose it should just be a string

2022-11-17 03:55 UTC, Teinble requested changes
You should check the website I post in one of the review. Use that example for all the java doc for your function. Thank you.

2022-11-17 03:55 UTC, Teinble commented on src/use_cases/UserUseCaseInteractor.java
> +        return "UsernameError";
Where are the other errors?

2022-11-17 03:55 UTC, Teinble commented on src/use_cases/UserUseCaseInteractor.java
>       * @return boo
This should not just specify the return value type. U can check the following example
https://www.oracle.com/ca-en/technical-resources/articles/java/javadoc-tool.html

2022-11-17 19:31 UTC, jasongangquanzhang commented on src/use_cases/UserUseCaseInteractor.java
> +    public String createUser(Map<String,ArrayList<String>> user){
I think that the value of the map should contain all the information the user entered when he wants to register a new account, which includes username, passward, reentered password, email. I think it is better to use a arraylist to store it.

2022-11-17 19:32 UTC, jasongangquanzhang commented on src/use_cases/UserUseCaseInteractor.java
> +        return "UsernameError";
This is just the description before implement of the method. I wrote "UsernameError" here to avoid mistake alert.

2022-11-17 19:46 UTC, jasongangquanzhang commented on src/use_cases/UserUseCaseInteractor.java
> +    public String createUser(Map<String,ArrayList<String>> user){
Yes, you are right. I shall fix it.

2022-11-19 22:59 UTC, cang-xue approved these changes
I think not bad

2022-11-19 23:01 UTC, Teinble reviewed
Nice change

2022-11-19 23:01 UTC, Teinble approved these changes
Nice Change. I will prove

2022-11-19 23:02 UTC, merged