[+] implemented Report Usecase, Controller, and dataInterface, [*]refactored all the exceptions, [+] implemented a new function in Userusecase, modified javadoc of Userusecase.
CSC207-2022F-UofT/course-project-group-140-q-a-forum pull request #78
Opened 2022-11-30 05:50 UTC by jasongangquanzhang

- implemented `createReport `,`removeReport` methods in `ReportUseCaseInteractor` to create a new report and remove a report
- implemented `createReport `,`removeReport` methods in `ReportController` that calls the related method in `ReportUseCaseInteractor` and catch thrown Runtime exceptions.
- Refactored all exceptions and modified all related files. Now we have only 6 exceptions. Please check all methods, especially those in package `controllers`, that throw or catch exceptions as the name of exceptions may have changed.
- implemented a whole series methods including`sendEmail`, `createMimeMessage`, and `verifyEmail`. Now the user use case has the function to generate and send verification email and verify the verification number given by user.
- installed `activation-1.1.1.jar`, `javax.mail-1.5.1.jar`, `javax.mail-api-1.5.1.jar` to realize function above.
- updated `passwordCheck` in `UserUseCaseInteractor` that would check the format of password user entered. The password should have more than 8 digits, at least two numbers, and no `","`. The password cannot be all numbers.
- modified `resetPassword` method in `UserUseCaseInteractor`. Now it takes 4 parameters and will perform `duoPasswordCheck` to check the two new passwords user entered, and throw corresponding Exceptions.
- updated Javadoc for `UserUseCaseInteractor`, `ReportController`, `ReportUseCaseInteractor`, `ReportDataInterface`,
- updated `registerButtonActionPerformed` in `MakeAnAccount`. Just change the sequence in the code.

Pending Issues and controversies:
1. the exceptions included in `modifyCourseContent` in `CourseUseCaseInteractor` have changed to `WrongInforException`, but the function should call setter method in `Course` entity instead of `modifyCourseContent` in that entity, the later one sounds like a use case method.
2. `MakeAReport` is ready for implementation.

2022-11-30 06:32 UTC, HermesCui reviewed
1. You do not need to delete the code and paste it again.
2. Appropriate merge for redundant exceptions, and you merge all empty or not found exception to one NotFoundException.
3. Implement the email verification part.
4. Follow the formal java document, and add more information to explain parameters.

2022-11-30 06:32 UTC, HermesCui commented on src/main/java/controllers/CourseController.java
> -       return courseInteractor.getAllCoursesName();
Why would you just delete the code and paste it again in CourseController?

2022-11-30 06:32 UTC, HermesCui commented on src/main/java/controllers/UserController.java
> -    public User getUser(String userName){
Same question, Why would you just delete the code and paste it again?

2022-11-30 06:32 UTC, HermesCui commented on src/main/java/exceptions/NotFoundException.java
> +package exceptions;
Appropriate merge for redundant exceptions, and you merge all empty or not found exception to one NotFoundException.

2022-12-01 03:21 UTC, JY3150 requested changes
I have left comments where I think there are changes needed to be made. Please correct them.

2022-12-01 03:21 UTC, JY3150 commented on src/main/java/controllers/UserController.java
> +            return -1;
Please document what these numbers represent. Otherwise it would be really difficult for the person doing UIs to do his job.

2022-12-01 03:21 UTC, JY3150 commented on src/main/java/use_cases/UserUseCaseInteractor.java
> +            char c;
This function is incorrectly implemented. First, why would you initialize count to be 1 instead of 0? Secondly, your count < 2 check only works when the i'th character is a digit, if my password only contains letters, this check would not be executed at all. Besides, the nested ifs are really messy and difficult for reviewers to understand.

2022-12-01 03:21 UTC, JY3150 commented on src/main/java/use_cases/UserUseCaseInteractor.java
> +    public static MimeMessage createMimeMessage(Session session, String sendMail, String receiveMail, String subject,
I don't understand these functions but are you sure you want this method to be static?

2022-12-01 21:38 UTC, JY3150 requested changes

2022-12-01 21:38 UTC, JY3150 commented on src/main/java/use_cases/UserUseCaseInteractor.java
> +            for (int i = 0; i < password.length() - 1; i++) {
Would would i < length - 1 instead of length? For example, if length is 4, then i could only be 0, 1, 2. This causes problem since if the last symbol is a comma, then your method would not detect it.

2022-12-01 21:52 UTC, JY3150 approved these changes
Now it looks generally good to me. But please remember to document everything as you go and test before you submit a pull request. Otherwise it would take other team members a really long time to figure out what your codes are doing. Besides, you need to work on your coding style, the nested if's in one of your function is really messy and you can definitely simplify it (for example, check the length > 8 at the very end by returning length > 9 && some other conditions). Please avoid doing this and try best to make your codes more readable and clear.

2022-12-02 04:51 UTC, blairyeung requested changes
I think the removal of exception is generally good but the name of the exception shuold be WrongInfoException. Can you change that please?

2022-12-02 05:21 UTC, jasongangquanzhang commented
> I think the removal of exception is generally good but the name of the exception shuold be WrongInfoException. Can you change that please?

The name of the file has been refactored. Thank you!

2022-12-02 05:53 UTC, blairyeung approved these changes
Yep, the changes now looks good!

2022-12-02 17:50 UTC, JY3150 approved these changes
I have read through the files and they look okay with me as said in the previous approval. But next time, if you are doing multiple changes, please create multiple branches and submit multiple pull requests separately. This will make the process of reviewing (and modification) easier.

2022-12-02 18:41 UTC, merged