Database update & Serialization
CSC207-2022F-UofT/course-project-group-140-q-a-forum pull request #84
Opened 2022-12-07 04:54 UTC by blairyeung

## DatabaseGataway update
I just updated the class `DatabaseGateway` and `DatabaseDataHandler`. The following functions are added:
- [+] Add 'saveToFile' to serialize the current data in the database to a file.
- [+] Add 'readFromFile' to read the serialized data from the file, into the database.
- Both of the methods does not accept any argument parameters, keep this in mind!
The name of the file is `data.ser`. It is placed (currently) under the root folder.
To call these methods, please use the singleton `DatabaseGateway` and call `databaseGateway.saveToFile()` or `databaseGateway.readFromFile()`, respectively. 

## Implementation of Serialization
I just implemented the above updates and now our project can serialize its data and store them in the file `data.ser`.
The program will save its data upon any update of entities. 
Also, we you starts the program, you will be able to read the entities/data from the previous run. If there is no previous records, the program will create a new `data.ser` for data storage.

2022-12-07 05:12 UTC, Teinble commented
Also, I saw some methods' names are changed in this PR. Will these changes affect the other files?

2022-12-07 05:26 UTC, blairyeung commented
> Also, I saw some methods' names are changed in this PR. Will these changes affect the other files?

The changes are only in the databasegateway and will not affect the other functionalities. Also, the changes are only made on the parameters (i.e, change String to Integer), not the signature itself.

2022-12-07 16:20 UTC, JY3150 requested changes
In your change to test files, if you change the correct verification code needed for registering a user to random, none of the test would pass. Change the random number string back to the string "DebugCode" should suffice.

2022-12-07 16:49 UTC, JY3150 approved these changes
The problems in test are fixed.

2022-12-07 18:00 UTC, Teinble approved these changes
I checked this pr, it works fine. I will approve

2022-12-07 18:00 UTC, merged

2022-12-08 19:26 UTC, blairyeung commented on src/main/java/database/DatabaseGateway.java
> +        ArrayList<Post> posts = course.getPosts();
Solved